### ISSUE TITLE
Dataset Redistribution

### ISSUE THREAD

**Issue by duducheng** [PyJulie/MONICA#2]
Hi, great work on this codebase!

I'm the author of MedMNIST and noticed that this repository redistributes our dataset. Given that MedMNIST is shared under CC licenses, redistribution is allowed as long as FULL credit is provided and same licenses are kept.

If the dataset content hasn’t been modified, I highly recommend using the official MedMNIST API (pip install medmnist) for accessing the data, which includes built-in download functionality—perhaps a wrapper could be added on top of the official API. This approach helps maintain consistency and avoids potential "forks" under the same dataset name.

Additionally, it appears there are other datasets in this repo. I’d suggest reviewing their licenses to ensure compliance.

JC

**Comment by PyJulie** [comment]
Hi Thank you for your notification.

We have updated the readme document and made a relevant claim on the license.

If there is still any problem, please let me know!
