### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by jiaxian1-intel** [PyJulie/MONICA#3]
Hi,

Thanks for great work to put various long tail medical image datasets together. I am wondering if you have any pretrained model to test especially for isic2019 dataset.

**Comment by PyJulie** [comment]
Hi, 

Thank you for your interest in this work!

We trained 5 times (5 random seeds) for isic2019 dataset on ResNet/ViT/SwinTrans/ConvNext with imbalance ratios of 100/200/500 on more than 30 methods, so there will be more than 1,800 pre-trained models. So it might be a little difficult for us to upload all pretrained models. Could you please provide some details regarding some specific usage or experimental settings? e.g.,  imbalance ratio, backbone, or methodology.

**Comment by jiaxian1-intel** [comment]
> Hi,
> 
> Thank you for your interest in this work!
> 
> We trained 5 times (5 random seeds) for isic2019 dataset on ResNet/ViT/SwinTrans/ConvNext with imbalance ratios of 100/200/500 on more than 30 methods, so there will be more than 1,800 pre-trained models. So it might be a little difficult for us to upload all pretrained models. Could you please provide some details regarding some specific usage or experimental settings? e.g., imbalance ratio, backbone, or methodology.

Hi,

Can I have a ViT backbone with resampling method for all three imbalance ratio?

**Comment by jiaxian1-intel** [comment]
Also I trained with both isic_RS.yml and isic_GCL_2nd.yml configurations. Both gave extremely bad results. Can you provide the exact configuration as you have in your paper?

**Comment by jiaxian1-intel** [comment]
It seems for ISIC2019 dataset, it just takes about 1 hour to train so I guess I do not need your pretrained model. Thanks
